# Generated by Django 4.1.2 on 2022-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='image',
            field=models.ImageField(upload_to='app1/image'),
        ),
    ]
